# Generated by Django 5.0.6 on 2024-06-15 10:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None)),
            ],
        ),
    ]
