# Generated by Django 5.0.6 on 2024-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Smartphone', max_length=50),
            preserve_default=False,
        ),
    ]
