# Generated by Django 4.2.13 on 2024-06-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_tinder_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tinder_image_url',
            field=models.TextField(null=True),
        ),
    ]
